import { Button, Container, TextField } from '@mui/material'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import { useState } from 'react'





//const Marker = dynamic(() => import("../../components/Marker"), { ssr: false });
const Map = dynamic(() => import("../../components/map"), { ssr: false });

export default function Converter() {
    const [latM, setLatM] = useState()
    const [lngM, setLngM] = useState()
    const [latD, setLatD] = useState()
    const [lngD, setLngD] = useState()

    const [markers, setMarkers] = useState([])

    
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Container sx={{ display: 'flex', flexDirection: 'column' }}>
                    <Container sx={{ display: 'flex', py: 4, gap: 2, justifyContent: 'center' }}>
                        <TextField variant='outlined' label="Lat (meters)" onChange={(e) => {
                            setLatM(e.target.value)
                        }} />
                        <TextField variant='outlined' label="Lon (meters)" onChange={(e) => {
                            setLngM(e.target.value)
                        }} />
                    </Container>
                    <Container sx={{ display: 'flex', gap: 2, justifyContent: 'center' }}>
                        <TextField variant='outlined' label="Lat (degrees)" onChange={(e) => {
                            setLatD(e.target.value)
                        }} />
                        <TextField variant='outlined' label="Lon (degrees)" onChange={(e) => {
                            setLngD(e.target.value)
                        }} />
                    </Container>

                    <Container sx={{ display: 'flex', justifyContent: 'center', py: 2, justifyContent: 'center' }}>
                        <Button variant="contained" onClick={() => {
                            console.log({ latD, lngD, latM, lngM })
                            // let tempMarker = Mark({coordinates:[34.4343,-12.334],id:"2121",title:"SKI"})
                            //setMarkers([...markers,tempMarker])
                        }}>
                            Convert
                        </Button>
                    </Container>

                </Container>
                <Container sx={{ p: 0, display: 'flex', justifyContent: 'center' }}>
                    <Map />
                </Container>


            </main>


        </div>
    )
}

