import {
  Container,
  Typography,
  CardContent,
  CardMedia,
  Grid,
  Box,
  Button
} from "@mui/material";
import Head from "next/head";
import Image from "next/image";
//import Image from 'next/image'
//import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Grid container
          maxWidth={true}
          sx={{
            display: "flex",
            justifyContent: "space-around",
            gap: 6,
            flexWrap: "wrap",
          }}
        >
          <Grid item
            sx={{
              display: "flex",
              flexDirection: "column",
              gap: 1,
              justifyContent: "center",
              height: 450,
            }}
          >
            <Typography variant="h1" >Spend less time</Typography>
            <Typography variant="h1">Do more !!!</Typography>
            <Button href="/tools" sx={{borderRadius:0,width:150}} variant="contained" color="primary">Explore Tools</Button>
          </Grid>
          <Grid item sx={{display:'flex',py:4}}>
            <Image
              src={
                "https://res.cloudinary.com/attic-gis/image/upload/v1656446620/energy_pbuhs9.png"
              }
              height={450}
              width={450}
              alt="hero"
            />
          </Grid>
        </Grid>
      </main>

      <footer></footer>
    </div>
  );
}
